# Generated by Django 4.1.7 on 2023-05-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_recurring_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_invoice',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
    ]
